### ISSUE TITLE
tent problem error

### ISSUE THREAD

**Issue by Pasterz19** [Southclaw/ScavengeSurvive#114]
SS/Core/World/Tent.pwn(756) : error 017: undefined symbol "AllocNextItemID"
SS/Core/World/Tent.pwn(758) : error 017: undefined symbol "SetItemNoResetArrayData"
SS/Core/World/Tent.pwn(763) : error 017: undefined symbol "CreateItem_ExplicitID"
SS/Core/World/Tent.pwn(763) : warning 215: expression has no effect
SS/Core/World/Tent.pwn(763) : error 029: invalid expression, assumed zero
SS/Core/World/Tent.pwn(763) : warning 226: a variable is assigned to itself (symbol "world")
SS/Core/World/Tent.pwn(763) : error 029: invalid expression, assumed zero
SS/Core/World/Tent.pwn(763) : fatal error 107: too many error messages on one line

Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

6 Errors.

Please help

**Comment by viruxe** [comment]
Would be nice if you could tell how you fixed it.
