### ISSUE TITLE
Help me to fix this Issue ( HackDetect.pwn , Prototype , Never User Symbol )

### ISSUE THREAD

**Issue by miqbalas** [Southclaw/ScavengeSurvive#118]
Nice and Awesome script!. but i still have a little problem here...
"
D:\SCRIPTIQBAL\ScavengeSurvive-master\pawno\include\Zipline.inc(505) : warning 217: loose indentation
SS/Core/Admin/HackDetect.pwn(553) : error 025: function heading differs from prototype
D:\SCRIPTIQBAL\ScavengeSurvive-master\gamemodes\ScavengeSurvive.pwn(127) : warning 204: symbol is assigned a value that is never used: "Chair"

Can you give some solutions?.

**Comment by Southclaw** [comment]
Outdated dependencies.
