### ISSUE TITLE
Multi Language

### ISSUE THREAD

**Issue by PatchwerkQWER** [Southclaw/ScavengeSurvive#119]
Hi, 
when someone translate the parts of gamemode (ex. tutorial) and he download a newer version, he must again translate the parts. So maybe is good idea add dynamically text loaded from JSON.

ex.
  "messages":{
    "tutorial":[
      "first part of tutorial ",
      "second part of tutorial...",
      "..."
    ]
   "itemtips":[
...
]
  },

I think it's better and easier than y_lang. What you think? This GM doesn't have a lot of texts so it can be quick recode. Or can I code it and pull commit?

**Comment by Southclaw** [comment]
Yes I've wanted to add this for a long time so people don't have to edit the source. I'll try to get around to it and write a module for languages. I may use y_language or write my own.

**Comment by PatchwerkQWER** [comment]
I made simple MultiLanguage system. http://pastebin.com/8gb9EWfP I think GVar is the best way (better than setproperty). 

Today i can add something line "\\" = next line and maybe multiline

**Comment by NeoPhoenix** [comment]
Strings with placeholders for variables may be a problem though (because of different sentence structures in different languages so variables might have a different order)

**Comment by Southclaw** [comment]
I might be able to come up with a solution for that.

**Comment by SizableRapter** [comment]
What about using something like CodeIgniter or Laravel, with a "Language" folder with sub-languages and string place holders for specific things.

```
"AntiCheat_Connected" => "Anti-Cheat Enabled/Connected"
```

**Comment by kadaradam** [comment]
How would you make the multi language system? Because i want to add english lang to my server as well and i'am planning to do this a year now, I made a simple script last year with GVar, but i stopped developing it, because the speed was much slower then SendClientMessage (ofc it's slower, it can't be faster, but there was a huge speed difference between the 2)

I don't have any idea, how would be the best to make it fast, because the speed is important, there are SCM almost everywhere. Another option is storing the strings in arrays, but it would generate lots of memory, especially if your gamemode has lots of strings and uses more than 2 languages.

**Comment by Southclaw** [comment]
If memory is a concern, SS is not the right gamemode! There are arrays above 50KB in size!
I've been playing with some quick string search code that can find the correct string given a key in a list of 32400 entries of 6 different languages:
```
Beginning search tests for random keys
[1ms] ret: 8104
[0ms] ret: 6856
[1ms] ret: 8703
[3ms] ret: 10663
[1ms] ret: 7025
[2ms] ret: 9577
[0ms] ret: 5723
[3ms] ret: 10266
[3ms] ret: 10475
[3ms] ret: 10206
Beginning search tests for specific lang 5
[3ms] ret: 10298
[2ms] ret: 8952
[2ms] ret: 7878
[2ms] ret: 8289
[0ms] ret: 5832
[1ms] ret: 5526
[1ms] ret: 6870
[2ms] ret: 8911
[2ms] ret: 8133
[1ms] ret: 8047
Beginning search tests for non-existent keys
[3ms] ret: -1
[3ms] ret: -1
[3ms] ret: -1
[3ms] ret: -1
[3ms] ret: -1
[3ms] ret: -1
[3ms] ret: -1
[4ms] ret: -1
[3ms] ret: -1
[3ms] ret: -1
```

I'll try and get this implemented next, writing the code will be quick but replacing all the string literals in the gamemode will take some time!

```
#include <a_samp>


#define MAX_LANGUAGE			(6)
#define MAX_LANGUAGE_NAME		(32)
#define MAX_LANGUAGE_ENTRIES	(32400)
#define MAX_LANGUAGE_KEY_LEN	(32)
#define MAX_LANGUAGE_VAL_LEN	(128)


enum E_LANGUAGE_DATA
{
	lang_name[MAX_LANGUAGE_NAME],
	lang_short[3],
	lang_index,
	lang_totalEntries
}

enum e_LANGUAGE_ENTRY_DATA
{
	lang_langID,
	lang_key[MAX_LANGUAGE_KEY_LEN],
	lang_val[MAX_LANGUAGE_VAL_LEN]
}

static
	lang_Data[MAX_LANGUAGE][E_LANGUAGE_DATA],
	lang_List[MAX_LANGUAGE_ENTRIES][e_LANGUAGE_ENTRY_DATA];


// TEST CODE
static
		keys[MAX_LANGUAGE_ENTRIES / MAX_LANGUAGE][MAX_LANGUAGE_KEY_LEN];
public OnFilterScriptInit()
{
	new curlang;

	for(new i; i < sizeof(keys); i++)
	{
		makerandstr(keys[i], MAX_LANGUAGE_KEY_LEN, 65, 'Z');
	}

	for(new i; i < MAX_LANGUAGE_ENTRIES; i++)
	{
		if(lang_Data[curlang][lang_index] == MAX_LANGUAGE_ENTRIES / MAX_LANGUAGE)// || random(100) < 60)
		{
			curlang++;
		}

		lang_List[i][lang_langID] = curlang;
		strcat(lang_List[i][lang_key], keys[lang_Data[curlang][lang_index]], MAX_LANGUAGE_KEY_LEN);
		makerandstr(lang_List[i][lang_val], MAX_LANGUAGE_VAL_LEN);

		lang_Data[curlang][lang_totalEntries]++;

		//printf("%02d/%d Index: %d [%d]: '%s':'%s'", i, MAX_LANGUAGE_ENTRIES, lang_Data[curlang][lang_index], lang_List[i][lang_langID], lang_List[i][lang_key], lang_List[i][lang_val]);

		lang_Data[curlang][lang_index]++;
	}

	// search tests

	new idx;
	new lang;
	new tmp[MAX_LANGUAGE_KEY_LEN];
	new buffer[MAX_LANGUAGE_VAL_LEN];
	new ret;

	new tick, final;

	print("Beginning search tests for random keys");
	for(new i; i < 10; i++)
	{
		idx = random(MAX_LANGUAGE_ENTRIES);
		lang = random(MAX_LANGUAGE);
		tick = GetTickCount();
		ret = GetLanguageString(lang, lang_List[idx][lang_key], buffer);
		final = GetTickCount() - tick;

		printf("[%dms] ret: %d", final, ret);
	}

	lang = random(MAX_LANGUAGE);
	printf("Beginning search tests for specific lang %d", lang);
	for(new i; i < 10; i++)
	{
		idx = random(MAX_LANGUAGE_ENTRIES);
		tick = GetTickCount();
		ret = GetLanguageString(lang, lang_List[idx][lang_key], buffer);
		final = GetTickCount() - tick;

		printf("[%dms] ret: %d", final, ret);
	}

	print("Beginning search tests for non-existent keys");
	for(new i; i < 10; i++)
	{
		idx = random(MAX_LANGUAGE_ENTRIES);
		lang = random(MAX_LANGUAGE);
		makerandstr(tmp, MAX_LANGUAGE_KEY_LEN);
		tick = GetTickCount();
		ret = GetLanguageString(lang, tmp, buffer);
		final = GetTickCount() - tick;

		printf("[%dms] ret: %d", final, ret);
	}
}
makerandstr(str[], len, start = 32, end = 'z')
{
	for(new i; i < len - 1; i++)
		str[i] = start + random(end - start);
}
// END TEST CODE

// Where the magic happens
stock GetLanguageString(languageid, key[], buffer[MAX_LANGUAGE_VAL_LEN])
{
	for(new i = lang_Data[languageid][lang_index]; i < lang_Data[languageid][lang_index] + lang_Data[languageid][lang_totalEntries]; i++)
	//for(new i; i < MAX_LANGUAGE_ENTRIES; i++) // this is the slow way: loop the entire list.
	{
		if(!strcmp(lang_List[i][lang_key], key))
		{
			buffer[0] = EOS;
			strcat(buffer, lang_List[i][lang_val]);
			return i;
		}
	}

	return -1;
}
```

**Comment by kadaradam** [comment]
Is it a good idea to use loop every time, when you send a message to a player?

Best way would be to make a plugin for this in c++. You can change the size of the array there, so you could save some memory. But sadly im not a c++ expert. :\

**Comment by PatchwerkQWER** [comment]
Size of the array is the reason why i use GVar and of course, i think it's not a good idea to use loop every time :) 

stock GetMessage(playerid,key[]){
        new str[1030];
        GetGVarString(name, key, 1030, PlayerLanguage[playerid]);
        return str;
}

**Comment by Southclaw** [comment]
Any sort of search will loop eventually (unless it's a direct address, which isn't possible when a string is the index/key or "search term"). I will implement hash maps (which PVars/GVars already use) to speed it up further and see how it is. Keep in mind those tests above are on 32400 entries, I doubt there would be that many entries for every language. As for heap memory, it's not really a concern at all; modders will likely care more about amount of languages than amount of entries since the source code controls that (unless a modder makes a full conversion mod, in which case they will be editing the source files anyway).

Still, if PVars (or GVars) are faster I'll use those but I'd rather not add another plugin to the dependency list.

If anyone wants to start translating now, translate the item names from ```./gamemodes/Core/Server/Init.pwn``` first (there are 201 items!) and write them into Gist/Pastebin as a start.

**Comment by Southclaw** [comment]
_Update: I'm actually working on this now!_

**Comment by Southclaw** [comment]
Module now added, discussion continued in #201
