### ISSUE TITLE
SaveLoad.pwn/HackDetect.pwn (553 Line)

### ISSUE THREAD

**Issue by DarkQuery** [Southclaw/ScavengeSurvive#120]
Hi, I have problems with SS. When compiling Pawn wrote me an error. Do you know anyone help?

1.http://prntscr.com/5wdldb  (SaveLoad.pwn)
2. SS/Core/Admin/HackDetect.pwn(553) : error 025: function heading differs from prototype (HackDetec.pwn)

Thank you for your expression

**Comment by PatchwerkQWER** [comment]
If you set up all the dependencies correctly, there should be no errors at all. If you have a problem compiling DON'T SUBMIT AN ISSUE HERE! that place is reserved for actual bugs.

**Comment by SizableRapter** [comment]
He's free to create an issue about that script not compiling on his system.

Fixes:
- Update your dependency of the script (most upto date version)
- Update the includes, all versions and links are given in the main ScavengeSurvive.pwn file.

**Comment by SizableRapter** [comment]
He's free to create an issue about that script not compiling on his system.

Fixes:
- Update your dependency of the script (most upto date version)
- Update the includes, all versions and links are given in the main ScavengeSurvive.pwn file.

**Comment by DarkQuery** [comment]
I downloaded the new files to the SS and I downloaded the new YSI 0.3z 3.1 RC5 but nothing changed, same error

**Comment by Southclaw** [comment]
Readme:
> If you have a problem compiling DON'T SUBMIT AN ISSUE HERE! that place is reserved for actual bugs.

YSI handles hooking, the issue resides there. Use the latest 3.1 version and it will work.
