### ISSUE TITLE
Weapon Rack Suggestion

### ISSUE THREAD

**Issue by Southclaw** [Southclaw/ScavengeSurvive#121]
From HotShot:

> I'd like a weapon rack, it's just off the top of my head. A weapon rack holds one weapon of your choice, you have the weapon rack screwed or hammered to the ground and can be removed with a crowbar. You interact with it by holding a weapon in hands and simply pressing return. The weapon is then displayed on the rack and can be quickly removed by press return. This way you could have several of them in a base, and when you need your weapon in an emergency you quickly run over and press return to take it, a nice new way to store weapons.

**Comment by SizableRapter** [comment]
I would prefer using a Four Tier system, allowing you to store Four Weapon on a rack, this could bring in a few new Mechanics, Wood, Metal, Smelting and so on.

Screws: Using Metal you need to smelt it and make them into Screws to make the following
Wood: Using wood you can create the following

- Foundations
- Supports
- Walls
- Windows
- Doors 

We could make a system that uses the Players Location to display it like Rust, and snapping. It may take a little work but to be honest it would bring a slightly more Fun building experience for Custom Bases, but keeping the old Building system with some improvements using the Edit functions. Along with this will bring a system for Mapping out the objects in 'Project X' (thoughts on the mapping bases in 3D in 'Project X'?

**Comment by Southclaw** [comment]
Completely forgot about this thread, turns out this is the direction I'm taking the project anyway! 

and yes, the weapon rack is happening for sure.

**Comment by Southclaw** [comment]
Dev note: Weapon rack item should be a 1 slot container with `displayonuse = false`, when used with an item the item is added, when interacted with the item is given back. Simple!

**Comment by Southclaw** [comment]
![image](https://cloud.githubusercontent.com/assets/1636971/20014340/8b63b360-a2ae-11e6-81a2-0d8242da541d.png)
