### ISSUE TITLE
Duplicate Spawn item With Inventory

### ISSUE THREAD

**Issue by DarkQuery** [Southclaw/ScavengeSurvive#128]
Hello friends, I have a big problem with inventory in the SS. Inventory and items in it began to duplicate. Please redress and bug fix.

 (Download the latest updates SS) 31.1.2015

Video: https://www.youtube.com/watch?v=FwXObS8svbI&ab_channel=DarkQuery

**Comment by Southclaw** [comment]
https://github.com/Southclaw/ScavengeSurvive/blob/a144faea00b586a14c853874f126c03fca63c34d/gamemodes/SS/Core/Char/Inventory.pwn#L501-L594

**Comment by Southclaw** [comment]
Works for me on latest version.
