### ISSUE TITLE
Some errors[Help]

### ISSUE THREAD

**Issue by KevinHendrews** [Southclaw/ScavengeSurvive#131]
Hey when I try to compile I get errors on this line:
Function header differs from prototype = 

public OnUnoccupiedVehicleUpdate(vehicleid, playerid, passenger_seat, Float:new_x, Float:new_y, Float:new_z, Float:vel_x, Float:vel_y, Float:vel_z)

Undefined Symbol
CreateNewSprayTag(In the maps file like LS.pwn etc);

**Comment by volfikcz** [comment]
1. you add hook OnUnocc..
2.You download new latesfike SS.

**Comment by KevinHendrews** [comment]
SS? I just downloaded it yesterday, SS = Scavenge Survive Master Pack right?
or sif?

**Comment by DarkQuery** [comment]
SIF too

**Comment by KevinHendrews** [comment]
Solved[CLOSED]

**Comment by KevinHendrews** [comment]
Solved[CLOSED]

**Comment by KevinHendrews** [comment]
Solved[CLOSED]

**Comment by KevinHendrews** [comment]
Solved[CLOSED]
