### ISSUE TITLE
Change Tents, Defences and Vehicles to runtime-save only, no more on-exit saving

### ISSUE THREAD

**Issue by Southclaw** [Southclaw/ScavengeSurvive#132]
Seems to cause problems possibly related to a stack corruption during the exit sequence.

Add "active" flag to all these saved entities.

On vehicle destroy, update file to be inactive but don't delete (can come in handy for debugging and recovering vehicles lost via bugs).

**Comment by Kar2k** [comment]
Good, reduce the load under OnPlayerDisconnect, it really does slow down your server.

When items are updated, set a flag to 'active', when the next update sequence is called (timer update or disconnect), update the active variables, ignoring the inactive ones. Thus reducing server load and any stack/heap risks.
