### ISSUE TITLE
Server lag and stops

### ISSUE THREAD

**Issue by KevinHendrews** [Southclaw/ScavengeSurvive#135]
Guys, Sometimes I start my server it stops working after some hours, Also the server lags sometimes..
Like host lag..
It is hosted at HapHost
128 MB Ram Linux/CentOS5
Server.cfg
echo Executing Server Config...
lanmode 1
rcon_password ***************************
maxplayers 1
port 7777
hostname Test
gamemode0 ScavengeSurvive
filterscripts 
plugins CTime dns FileManager irc socket sscanf streamer Whirlpool
announce 1
query 1
chatlogging 1
weburl www.sa-mp.com
onfoot_rate 40
incar_rate 40
weapon_rate 40
stream_distance 300.0
stream_rate 1000
maxnpc 0
logtimeformat [%H:%M:%S]

**Comment by Southclaw** [comment]
Can you elaborate on "stops working"? Does it crash? Use crashdetect and gdb to track the cause.

As for performance, 128MB probably isn't enough to run SS, there are thousands of entities loaded during runtime but you could try lowering the vehicle spawn rate and loot spawn rate so less will be loaded on each restart but after players start building bases, saving items tents and boxes and keeping vehicles, you're probably not going to have enough memory left.

**Comment by KevinHendrews** [comment]
k well... How will I lower those rates? Where are they defined in the script?

**Comment by Southclaw** [comment]
settings.json
