### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jerry121** [Southclaw/ScavengeSurvive#136]
SS/Core/Admin/HackDetect.pwn(553) : error 025: function heading differs from prototype
ss/World/Zones/LS.pwn(38) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/LS.pwn(39) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/LS.pwn(40) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/LS.pwn(41) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/LS.pwn(42) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/SF.pwn(36) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/SF.pwn(37) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/SF.pwn(38) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/SF.pwn(39) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/BC.pwn(43) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/BC.pwn(44) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/BC.pwn(45) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/TR.pwn(24) : error 017: undefined symbol "CreateNewSprayTag"
ss/World/Zones/TR.pwn(25) : error 017: undefined symbol "CreateNewSprayTag"
C:\Users\Jarko\Desktop\SAAMP\gamemodes\ScavengeSurvive.pwn(597) : warning 204: symbol is assigned a value that is never used: "gWorld"
Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase
Help please !

**Comment by Southclaw** [comment]
> If you have a problem compiling DON'T SUBMIT AN ISSUE HERE! that place is reserved for actual bugs.

If a version has errors, simply use an earlier version.
