### ISSUE TITLE
error help SouthClaw

### ISSUE THREAD

**Issue by thanhgom1611996** [Southclaw/ScavengeSurvive#137]
SS/Core/Vehicle/PlayerVehicle.pwn(183) : error 035: argument type mismatch (argument 3)
SS/Core/Vehicle/PlayerVehicle.pwn(305) : error 035: argument type mismatch (argument 3)
SS/Core/Vehicle/PlayerVehicle.pwn(351) : error 035: argument type mismatch (argument 3)
SS/Core/Vehicle/PlayerVehicle.pwn(394) : error 035: argument type mismatch (argument 3)
SS/Core/Player/SaveLoad.pwn(265) : error 035: argument type mismatch (argument 3)
SS/Core/Player/SaveLoad.pwn(398) : error 035: argument type mismatch (argument 3)
SS/Core/Player/SaveLoad.pwn(416) : error 035: argument type mismatch (argument 3)
SS/Core/Player/SaveLoad.pwn(432) : error 035: argument type mismatch (argument 3)
SS/Core/Player/SaveLoad.pwn(469) : error 035: argument type mismatch (argument 3)
SS/Core/Char/Drugs.pwn(296) : error 035: argument type mismatch (argument 3)
SS/Core/Char/Infection.pwn(102) : error 035: argument type mismatch (argument 3)
SS/Core/Weapon/damage.core.pwn(462) : error 035: argument type mismatch (argument 3)
SS/Core/World/Defences.pwn(108) : error 035: argument type mismatch (argument 3)
SS/Core/World/Defences.pwn(1375) : error 035: argument type mismatch (argument 3)
SS/Core/World/Defences.pwn(1386) : error 035: argument type mismatch (argument 3)
SS/Core/World/SafeBox.pwn(582) : error 035: argument type mismatch (argument 3)
SS/Core/World/SafeBox.pwn(605) : error 035: argument type mismatch (argument 3)
SS/Core/World/SafeBox.pwn(631) : error 035: argument type mismatch (argument 3)
SS/Core/World/Tent.pwn(638) : error 035: argument type mismatch (argument 3)
SS/Core/World/Tent.pwn(646) : error 035: argument type mismatch (argument 3)
SS/Core/World/Tent.pwn(684) : error 035: argument type mismatch (argument 3)
SS/Core/Admin/HackDetect.pwn(553) : error 025: function heading differs from prototype
C:\Documents and Settings\Admin\Desktop\ScavengeSurvive\gamemodes\ScavengeSurvive.pwn(597) : warning 204: symbol is assigned a value that is never used: "gWorld"
Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

22 Errors.

**Comment by thanhgom1611996** [comment]
Help full pawno include ? State Vietnam

**Comment by Southclaw** [comment]
Readme:
> If you have a problem compiling DON'T SUBMIT AN ISSUE HERE! that place is reserved for actual bugs.

If a version has errors, simply use an earlier version.

**Comment by DarkQuery** [comment]
I have the same, do not know anyone advice how to fix it?
