### ISSUE TITLE
Fix vehicle interaction entry animation desync

### ISSUE THREAD

**Issue by Southclaw** [Southclaw/ScavengeSurvive#143]
Lock all vehicles for each player unless they walk near the door of the closest vehicle and it's not locked externally.

**Comment by PT-Player** [comment]
@Southclaw what is the point of do this?

**Comment by Southclaw** [comment]
If a player tries to enter a vehicle (with F or G) while they are standing 10m from it, it seems that SA:MP syncs this to other players before SetPlayerPos/TogglePlayerControllable/etc. What happens is, if a player presses F to interact with something else while near a vehicle, other players sometimes see that player running to the vehicle and entering it even if the player doesn't do that on their screen.

This fix locks all vehicles and only unlocks them if you walk closer. I will need to test it more with other players to ensure there are no problems with specific vehicle types but it appears to be working pretty perfectly so far.

**Comment by viruxe** [comment]
Ah, this was much needed.
