### ISSUE TITLE
Kicks sometimes don't save properly due to function call timing

### ISSUE THREAD

**Issue by Southclaw** [Southclaw/ScavengeSurvive#150]
Sometimes (seemingly rarely) by the time the save function is called, the player has already disconnected and their ID is invalid, resulting in failed GetPlayerName calls.

**Comment by KevinHendrews** [comment]
Well it would be good to add a system which saves your account every 1 minute or 10 mins

**Comment by Southclaw** [comment]
https://github.com/Southclaw/ScavengeSurvive/blob/master/gamemodes/SS/Core/Server/Autosave.pwn

**Comment by Southclaw** [comment]
This issue is now over a year old and I haven't seen this problem appear for a long time.
