### ISSUE TITLE
SAMPSON & JSON

### ISSUE THREAD

**Issue by DarkQuery** [Southclaw/ScavengeSurvive#152]
I have an issue with SAMPSON Lists to log into the server Warning here

http://prntscr.com/6xm5c9

The chat server to spamming whole chatbox as second

(Rule 1) Please update the 'server / rules' array in ...

**Comment by viruxe** [comment]
You will have to either figure it out for yourself on how to make SAMPSON work or find another JSON plugin to correctly enable read and write operations on JSON files as SAMPSON only suports reading and is still experiemental in this gamemode.

Unfortunatly Southclaw doesn't have the habit to use branches.

**Comment by Southclaw** [comment]
Redundant since the switch to INI.
