### ISSUE TITLE
Accounts bug

### ISSUE THREAD

**Issue by HardGZ** [Southclaw/ScavengeSurvive#156]
In the lastest version, I registered a user, I logged of and I changed my nickname, I joined the server and it says: (kick: An error occurred while executing statement 'stmt_AccountCreate'. Please contact an admin on IRC or the forum.)

So you only can create 1 user.

**Comment by Southclaw** [comment]
This happens when stmt_execute fails. After adding the error I noticed the database file I was using didn't have readwrite permissions (664) so ensure you ```chmod``` and ```chown``` the file.

**Comment by HardGZ** [comment]
Now works, thank you!
