### ISSUE TITLE
Spawn Bug

### ISSUE THREAD

**Issue by IntenseGaming** [Southclaw/ScavengeSurvive#159]
When you submit your name and level on accounts.db,you will freeze and the attachements/toys not loaded.
And also if i change any setting in settings.ini,it will bug too

**Comment by Southclaw** [comment]
Do not enter raw information to accounts.db, log in through the game client.

This works as expected for me on both Linux and Windows server versions.

If there's a problem with settings.ini loading, please post it in a separate issue report.

**Comment by IntenseGaming** [comment]
then,how do i make myself admin?

**Comment by Southclaw** [comment]
Log in as RCON, "/adminlvl".
