### ISSUE TITLE
Freeze related to settings.ini

### ISSUE THREAD

**Issue by IntenseGaming** [Southclaw/ScavengeSurvive#160]
um,when i change the settings on setting.ini,it will be freeze bug.
can you help me?

**Comment by Southclaw** [comment]
Please write more descriptive issue titles and bodies!

What do you mean by freeze bug? What setting are you changing in the settings file? When does this happen? How can I reproduce this?

**Comment by IntenseGaming** [comment]
i change the MOTD and website textdraw
