### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by darkhunter332** [Southclaw/ScavengeSurvive#161]
3 issues,
1,I dont have those files,
[19:52:13] ERROR: key 'server/rules/0' not found.
[19:52:13] ERROR: key 'server/staff/0' not found.
And i want to change things in rules,Staff team etc,
2,When i go to sss/settings i dont see infomessages,
3.Health/knockout system isn't working well.

(I will be happy if anyway will send me a better gm sas with no bugs)

**Comment by Southclaw** [comment]
Please add details to issue reports and write ONE issue per report. There's no need to duplicate issue reports.
