### ISSUE TITLE
Long starting

### ISSUE THREAD

**Issue by PatchwerkQWER** [Southclaw/ScavengeSurvive#162]
Hi,

This gamemode take a lot of time when everything is loaded, created, generated etc. But you can connect immediately. Yes, connect but it doesn't join you to the game. It's confusion for people that doesn't know that. 

Solution:
In `OnGameModeInit_Setup` just add `SendRconCommand("password SOMETHING_MAYBE_GENERATED");` and to the latest `OnGameModeInit` add `SendRconCommand("password 0");`

It's all. When server is started he will be locked and when the server is ready for play he will be automatic unlocked :)

Cheers

**Comment by Southclaw** [comment]
This change was made so there would be a buffer time for players to connect after loading but before loot placement (the world scripts are activated *after* all the other initiation code, which also eases the changeability of world scripts).

Adding an RCON password would complicate things further as players might think the server is passworded permanently and they would have to leave the server to retry.

I planned to add client messages or an ActionBar instance indicating world loading progress. I'll put this on the todo list for the next update.

**Comment by Southclaw** [comment]
Fixed this issue in 7974936fd9b372f15dbde1facfc3d598123a65c1 sorry it took so long :)

**Comment by PatchwerkQWER** [comment]
No problem. Welcome back :)
