### ISSUE TITLE
Gamemode wont load

### ISSUE THREAD

**Issue by Gigel01** [Southclaw/ScavengeSurvive#167]
I am a newbie at this scripting thing but i looked over tutorials on youtube and i coudant find a tutorial for gamemode . My problem is i do evriting i set plugin script gamemode but when i start up the server this error pops up :  I couldn't load any gamemode scripts. Please verify your server.cfg
It needs a gamemode0 line at the very least. Please help

**Comment by Southclaw** [comment]
This section is for code bugs with the gamemode.
I advise you start small with SA:MP, this is a very complex gamemode and you're unlikely to get support for it since it's not a widely used mode.
