### ISSUE TITLE
Server gamemode

### ISSUE THREAD

**Issue by Gigel01** [Southclaw/ScavengeSurvive#168]
Southclaw can you please explain why this gamemode isnt working . Can you make a tutorial ? PLZ or explain i realy want to play on this gamemode

**Comment by Patrik356b** [comment]
Can you provide more information?

**Comment by Gigel01** [comment]
When i start up the server its says no Gamemode have been found an something with gamemode0 parameters

**Comment by Southclaw** [comment]
You need to go and learn the basics of SA:MP servers without this mode, stop spamming the repo issues.
