### ISSUE TITLE
Script has some Errors

### ISSUE THREAD

**Issue by ArshmanAfzal** [Southclaw/ScavengeSurvive#171]
Its been two months i am trying to compile the script but it is not working, i am getting a issue and i think there is  a problem with the gamemode.

D:\COPS AND ROBBERS\samp037_svr_R1_win32\pawno\include\sqlitei.inc(969) : error 017: undefined symbol "db_get_mem_handle"
D:\COPS AND ROBBERS\samp037_svr_R1_win32\pawno\include\sqlitei.inc(978) : error 017: undefined symbol "db_get_mem_handle"
D:\COPS AND ROBBERS\samp037_svr_R1_win32\pawno\include\sqlitei.inc(2159) : error 017: undefined symbol "db_get_mem_handle"
SS/Core/World/WeaponsCache.pwn(113) : error 017: undefined symbol "drawdistance"
SS/Core/World/WeaponsCache.pwn(113) : warning 215: expression has no effect
SS/Core/World/WeaponsCache.pwn(113) : error 001: expected token: ";", but found ")"
SS/Core/World/WeaponsCache.pwn(113) : error 029: invalid expression, assumed zero
SS/Core/World/WeaponsCache.pwn(113) : fatal error 107: too many error messages on one line

Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

7 Errors.

**Comment by Southclaw** [comment]
This is not a problem with the code. Update the libraries of the functions the errors point to.

**Comment by ArshmanAfzal** [comment]
i did it doesnt work

**Comment by ArshmanAfzal** [comment]
many people are facing the same problem i think you must now Provide a solution for this.
