### ISSUE TITLE
IsPlayerInWater doesn't account for underground parking lots

### ISSUE THREAD

**Issue by Kar2k** [Southclaw/ScavengeSurvive#174]
^ Title.

E.G San Fierro PD Underground Parking Lot.

**Comment by Southclaw** [comment]
I can't believe I've never thought of that! That also means, as useless as it sounds, hackers could use the swimming-animation-flying mod in these places undetected.

I'll see about fixing this asap, thanks!

**Comment by Patrik356b** [comment]
Does it take into account the height difference between the two sides of the Sherman Dame? 

Also there is a couple of houses/buildings with pools using real water. 

LV has a hotel building near a Transfender shop with such a pool

**Comment by Southclaw** [comment]
Yeah all of that is already taken into account, code here: https://github.com/Southclaw/ScavengeSurvive/blob/6c163f417ce3cf43c3d0af43face1513f63f9beb/gamemodes/SS/utils/player.pwn#L169-L221

**Comment by Kar2k** [comment]
Yea. I'll help and post locations here in a few hours.

**Comment by ipsBruno** [comment]
You consider use IsPlayerInWeather with ColAndreas? Is very accurace.

Thank you.

**Comment by viruxe** [comment]
Using that libraby would only account for actual collisions. Water isn't considered as a collision by the game engine IIRC.
Anyway there shouldn't be many more areas left out to cover for this.

**Comment by ipsBruno** [comment]
ColAndreas.inc has a IsPlayerInWalter and IsPlayerInNearWalter  function

**Comment by Kar2k** [comment]
Would be really great to have an IsPlayerInWater function that doesn't rely on in-engine data though. To share for everyone.

**Comment by viruxe** [comment]
Oh, that is great. How accurate is it?

**Comment by ipsBruno** [comment]
It uses CA_RayCastMultiLine. The RayCast return exactly collision point and the object colided. In default, is 0.001 z difference to validate if Player in Water. About CA_IsPlayerNearWater, it check all collisions arround player (60° angle step by step), if has a colission and is water, return true,

That is great because don't need animations or areas postions, only collisions, and is very accurate.
Sorry my English,

**Comment by Southclaw** [comment]
ColAndreas is massive overkill for this job. Sure if a project uses ColAndreas anyway, you may as well use it. But if not, this function is sufficient. The only known problem with my function is this issue, which is easily fixed! (I just haven't got around to it!)
