### ISSUE TITLE
Problems with adding commands

### ISSUE THREAD

**Issue by darkhunter332** [Southclaw/ScavengeSurvive#177]
Hello there,
I tried to add few commands to the admin level 1-2
and i got issues,
I went to gamemodes-ss-core-admin1 and admin2 and pasted the commands i need,
But they don't work,Why?

**Comment by Southclaw** [comment]
I can't answer if you don't give any information. Tell me what issues you had, post your code etc. Ensure you are following the correct syntax for admin commands.

**Comment by darkhunter332** [comment]
Here it is:
http://prntscr.com/a9iz1p
I'm trying to add a command for admin level 1,
But somehow it doesn't work,
I also have issues with this:
http://prntscr.com/a9j0f3
It doesn't show me when i should get up from unconscious mode.
Sorry for not giving any info last time xd,
Thanks,.

**Comment by darkhunter332** [comment]
Here it is:
http://prntscr.com/a9iz1p
I'm trying to add a command for admin level 1,
But somehow it doesn't work,
I also have issues with this:
http://prntscr.com/a9j0f3
It doesn't show me when i should get up from unconscious mode.
Sorry for not giving any info last time xd,
Thanks,.
