### ISSUE TITLE
Problems compiling gamemode

### ISSUE THREAD

**Issue by tigogs** [Southclaw/ScavengeSurvive#179]
Hi SouthClaw. I'm having problems compiling the gamemode, I will put the errors and warnings below for you to try to help me, please. Sorry for my bad english =(

SS/Core/World/Tent.pwn(413) : warning 235: public function lacks forward declaration (symbol "OnItemArrayDataChanged")
SS/Core/Admin/NameTags.pwn(29) : error 035: argument type mismatch (argument 14)
SS/Core/Admin/NameTags.pwn(30) : error 035: argument type mismatch (argument 14)
SS/Core/Item/PlantPot.pwn(226) : warning 202: number of arguments does not match definition
SS/Core/Item/PlantPot.pwn(240) : warning 202: number of arguments does not match definition
SS/Core/Item/PlantPot.pwn(246) : warning 202: number of arguments does not match definition
Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

Lines : 
29 -	tags_Nametag[playerid] = CreateDynamic3DTextLabelEx(string, YELLOW, 0.0, 0.0, 0.0, 6000.0, playerid, _, 0, 6000.0, _, _, players, 1, 1, maxplayers);
30 - tags_NametagLOS[playerid] = CreateDynamic3DTextLabelEx("[|                                           |]", BLUE, 0.0, 0.0, 0.0, 6000.0, playerid, _, 1, 6000.0, _, _, players, 1, 1, maxplayers);

2 Errors.

**Comment by tigogs** [comment]
#140

**Comment by Southclaw** [comment]
[Read number 3.](https://github.com/Southclaw/ScavengeSurvive#setup)

You obviously don't have the required versions of the libraries those functions are from. CreateDynamic3DTextLabelEx is a streamer function, use the correct streamer version. OnItemArrayDataChanged is a SIF function, you may need to wait for a SIF update or just use an older version of SS that doesn't require this function.
