### ISSUE TITLE
Problem with ammunition in game

### ISSUE THREAD

**Issue by tigogs** [Southclaw/ScavengeSurvive#182]
Good night SouthClaw, I would write but it is difficult to explain through ... So I decided to make a video for you, I upload my gameplay channel PratesPlay, if you can help us, we would be very grateful, the Brazilian community thanks you and loves you very, very loved your game mode, and a fever here!

Update: I think it might be some incompatibility with the host we use, what do you think?

https://www.youtube.com/watch?v=06bpgP2IDPk&feature=youtu.be

**Comment by Southclaw** [comment]
That was probably the best bug report ever!

I'm assuming you've fixed this issue since you closed it. The problem was likely coming from OnPlayerWeaponShot not being called somehow resulting in the ammo value of the weapon item not being changed.
