### ISSUE TITLE
Anti-Cheat Extension

### ISSUE THREAD

**Issue by viruxe** [Southclaw/ScavengeSurvive#184]
From what I remember, we discussed that the ac part would be left out of this public repository but somehow it is included in the extensions directory.
This renders the current program useless.

P.S.: We should talk. Give me a way to IM you.

**Comment by Southclaw** [comment]
I have plans for a new AC anyway, with actual end-to-end encryption etc.

I don't really use much IM but I'm most active here: https://discord.gg/0TvwpQXGu5Jyo4LR
