### ISSUE TITLE
Country.pwn (iphub.info)

### ISSUE THREAD

**Issue by DarkQuery** [Southclaw/ScavengeSurvive#190]
Hi, I have a slight problem, I used the code from Scavenge Survive, I mean precisely this

[(https://github.com/Southclaw/ScavengeSurvive/blob/d3336c6083037a1f0c45614fde870f660a6b489a/gamemodes/sss/core/player/country.pwn)]

I rearranged it and remodeled it in order to use the include then I used it in my code, revamped to write the dialogue "Unknown" (I do not know if it works, I do not how to test). But when the script I use on a hosted server hosting, so it does not work, it still lists "Unknown or an empty string '' I do not know what to do was repeated, page http://iphub.info/api.php?ip= works fine , But it can not be.

http://i.imgur.com/W0nQ2Ta.png

Edited version:

http://i.imgur.com/FY7Y5wN.png

Hosted on the server (gamehosting) it does not work on localhost and also not.
This is my modified code (Include)

> `#include <a_samp>
> #include <a_http>
> #include <YSI/y_iterate>
> 
> #if !defined isnull
>     #define isnull(%1) ((!(%1[0])) || (((%1[0]) == '\1') && (!(%1[1]))))
> #endif
> 
> 
> enum E_COUNTRY_DATA
> {
> 			cntr_Hostname[60],
> 			cntr_Code[3],
> 			cntr_Country[92],
> 			cntr_Region[43],
> 			cntr_ISP[60],
> 			cntr_Proxy
> }
> 
> 
> static
> 			PlayerCountryData[MAX_PLAYERS][E_COUNTRY_DATA],
> 			PlayerLookupRetries[MAX_PLAYERS],
> 			PlayerSessionData[MAX_PLAYERS],
> Iterator:	PlayerSessionIndex<MAX_PLAYERS>;
> 
> static
> 			MaxRetries = 5;
> 
> 
> forward OnLookupResponse(sessionid, response, data[]);
> 
> 
> 
> 
> _cntr_HandleLogin(playerid)
> {
> 	_cntr_ClearData(playerid);
> 	_cntr_UseDatabase(playerid);
> 	_cntr_UseWeb(playerid);
> }
> 
> _cntr_ClearData(playerid)
> {
> 	PlayerCountryData[playerid][cntr_Hostname][0] = EOS;
> 	PlayerCountryData[playerid][cntr_Code][0] = EOS;
> 	PlayerCountryData[playerid][cntr_Country][0] = EOS;
> 	PlayerCountryData[playerid][cntr_Region][0] = EOS;
> 	PlayerCountryData[playerid][cntr_ISP][0] = EOS;
> 	PlayerCountryData[playerid][cntr_Proxy] = 0;
> }
> 
> _cntr_UseDatabase(playerid)
> {
> // Causes sqlitei errors for some reason, disabled for now.
> //	GetPlayerCountry(playerid, PlayerCountryData[playerid][cntr_Country], 45);
> 
> 	if(!strcmp(PlayerCountryData[playerid][cntr_Country], "Unknown"))
> 		return 0;
> 
> 	return 1;
> }
> 
> _cntr_UseWeb(playerid)
> {
> 	new
> 		cell,
> 		ip[16],
> 		query[60];
> 
> 	GetPlayerIp(playerid, ip, sizeof(ip));
> 	format(query, sizeof(query), "iphub.info/api.php?ip=%s", ip);
> 
> 	cell = Iter_Free(PlayerSessionIndex);
> 	PlayerSessionData[cell] = playerid;
> 	Iter_Add(PlayerSessionIndex, cell);
> 
> 	HTTP(cell, HTTP_GET, query, "", "OnLookupResponse");
> 
> 	return 1;
> }
> 
> public OnLookupResponse(sessionid, response, data[])
> {
> 	if(!(0 <= sessionid < MAX_PLAYERS))
> 	{
> 		printf("ERROR: OnLookupResponse sessionid out of bounds (%d)", sessionid);
> 		return;
> 	}
> 
> 	new playerid = PlayerSessionData[sessionid];
> 	Iter_Remove(PlayerSessionIndex, sessionid);
> 
> 	if(!IsPlayerConnected(playerid))
> 		return;
> 
> 	if(response != 200 || isnull(data))
> 	{
> 		if(PlayerLookupRetries[playerid] < MaxRetries)
> 		{
> 			PlayerLookupRetries[playerid]++;
> 			_cntr_UseWeb(playerid);
> 		}
> 
> 		return;
> 	}
> 
> 	new
> 		pos,
> 		proxy[2];
> 
> 	_cntr_GetXMLData(data, "host", PlayerCountryData[playerid][cntr_Hostname], pos, 60);
> 	_cntr_GetXMLData(data, "code", PlayerCountryData[playerid][cntr_Code], pos, 3);
> 	_cntr_GetXMLData(data, "country", PlayerCountryData[playerid][cntr_Country], pos, 92);
> 	_cntr_GetXMLData(data, "region", PlayerCountryData[playerid][cntr_Region], pos, 43);
> 	_cntr_GetXMLData(data, "isp", PlayerCountryData[playerid][cntr_ISP], pos, 60);
> 	_cntr_GetXMLData(data, "proxy", proxy, pos, 2);
> 
> 	PlayerCountryData[playerid][cntr_Proxy] = strval(proxy);
> 
> 	printf("[COUNTRY] Player country: '%s' (host: '%s' proxy: %d)",
> 		PlayerCountryData[playerid][cntr_Country],
> 		PlayerCountryData[playerid][cntr_Hostname],
> 		PlayerCountryData[playerid][cntr_Proxy]);
> 
> 	if(PlayerCountryData[playerid][cntr_Proxy])
> 	    SendClientMessage(playerid, -1, "Máš proxy");
> 		//KickPlayer(playerid, "Proxy connection detected, these are not allowed.");
> 
> 	return;
> }
> 
> _cntr_GetXMLData(string[], tag[], output[], &start, maxlength = sizeof(output))
> {
> 	new end = start = (strfind(string, tag, true, start) + strlen(tag) + 1);
> 
> 	while(string[end] != '<' && string[end] != '\0' && end - start < maxlength)
> 		end++;
> 
> 	strmid(output, string, start, end, maxlength);
> }
> 
> 
> stock GetPlayerCountryDataAsString(playerid, output[], len = sizeof(output))
> {
> 	if(!IsPlayerConnected(playerid))
> 		return 0;
> 
> 	format(output, len, "\
> 		HHostname: '%s'\n\
> 		Code: '%s'\n\
> 		Country: '%s'\n\
> 		Region: '%s'\n\
> 		ISP: '%s'\n\
> 		Proxy: %s",
> 		PlayerCountryData[playerid][cntr_Hostname],
> 		PlayerCountryData[playerid][cntr_Code],
> 		PlayerCountryData[playerid][cntr_Country],
> 		PlayerCountryData[playerid][cntr_Region],
> 		PlayerCountryData[playerid][cntr_ISP],
> 		PlayerCountryData[playerid][cntr_Proxy] ? ("Yes") : ("No"));
> 
> 	return 1;
> }
> 
> /*
> stock GetPlayerCountryDataAsString(playerid, output[], len = sizeof(output))
> {
>     new
>         hostname[30],
>         code[30],
>         country[30],
>         region[30],
>         isp[30],
>         proxy[30];
> 
>     if(!IsPlayerConnected(playerid))
>         return 0;
> 
>     if(strlen(PlayerCountryData[playerid][cntr_Hostname]) == 0) hostname = "Unknownnn";
>     else format(hostname, sizeof(hostname), "%s", PlayerCountryData[playerid][cntr_Hostname]);
> 
>     if(strlen(PlayerCountryData[playerid][cntr_Code]) == 0) code = "Unknown";
>     else format(code, sizeof(code), "%s", PlayerCountryData[playerid][cntr_Code]);
> 
>     if(strlen(PlayerCountryData[playerid][cntr_Country]) == 0) country = "Unknown";
>     else format(country, sizeof(country), "%s", PlayerCountryData[playerid][cntr_Hostname]);
> 
>     if(strlen(PlayerCountryData[playerid][cntr_Region]) == 0) region = "Unknown";
>     else format(region, sizeof(region), "%s", PlayerCountryData[playerid][cntr_Region]);
> 
>     if(strlen(PlayerCountryData[playerid][cntr_ISP]) == 0) isp = "Unknown";
>     else format(isp, sizeof(isp), "%s", PlayerCountryData[playerid][cntr_ISP]);
> 
>     if(strlen(PlayerCountryData[playerid][cntr_Proxy]) == 0) proxy = "Unknown";
>     else format(proxy, sizeof(proxy), "%s", PlayerCountryData[playerid][cntr_Proxy]);
> 
> 
>     format(output, len, "\
>         HHostname: '%s'\n\
>         Code: '%s'\n\
>         Country: '%s'\n\
>         Region: '%s'\n\
>         ISP: '%s'\n\
>         Proxy: %s",
>         hostname,
>         code,
>         country,
>         region,
>         isp,
>         proxy
>          ? ("Yes") : ("No"));
> 
>     return 1;
> }
> */
> // cntr_Hostname[60],
> stock GetPlayerCachedHostname(playerid, output[], len = sizeof(output))
> {
>     //if(!strcat(PlayerCountryData[playerid][cntr_Hostname], "Unknown")
> 	output[0] = EOS;
> 	strcat(output, PlayerCountryData[playerid][cntr_Hostname], len);
> 
> 	return 1;
> }
> 
> // cntr_Code[3],
> stock GetPlayerCachedCountryCode(playerid, output[], len = sizeof(output))
> {
> 	if(!IsPlayerConnected(playerid))
> 		return 0;
> 
> 	output[0] = EOS;
> 	strcat(output, PlayerCountryData[playerid][cntr_Code], len);
> 
> 	return 1;
> }
> 
> // cntr_Country[45],
> stock GetPlayerCachedCountryName(playerid, output[], len = sizeof(output))
> {
> 	if(!IsPlayerConnected(playerid))
> 		return 0;
> 
> 	output[0] = EOS;
> 	strcat(output, PlayerCountryData[playerid][cntr_Country], len);
> 
> 	return 1;
> }
> 
> // cntr_Region[43],
> stock GetPlayerCachedRegion(playerid, output[], len = sizeof(output))
> {
> 	if(!IsPlayerConnected(playerid))
> 		return 0;
> 
> 	output[0] = EOS;
> 	strcat(output, PlayerCountryData[playerid][cntr_Region], len);
> 
> 	return 1;
> }
> 
> // cntr_ISP[60],
> stock GetPlayerCachedISP(playerid, output[], len = sizeof(output))
> {
> 	if(!IsPlayerConnected(playerid))
> 		return 0;
> 
> 	output[0] = EOS;
> 	strcat(output, PlayerCountryData[playerid][cntr_ISP], len);
> 
> 	return 1;
> }
> 
> // cntr_Proxy
> stock IsPlayerUsingProxy(playerid)
> {
> 	if(!IsPlayerConnected(playerid))
> 		return 0;
> 
> 	return PlayerCountryData[playerid][cntr_Proxy];
> }
> 

Basic,.

> #include <a_samp>
> #include <zcmd>
> #include <base.pwn>
> 
> CMD:checkex2(playerid, params[])
> {
> 	new dating[255];
> 	GetPlayerCountryDataAsString(playerid, dating);
> 	ShowPlayerDialog(playerid, 4874, DIALOG_STYLE_MSGBOX, "Title", dating, "Zavřít", "");
> 	return 1;
> }
> 
> CMD:checkex(playerid, params[])
> {
>     new targetid, dat[255], checkexString[255], IpEx[20];
>     if(sscanf(params,"u", targetid)) return SendClientMessage(playerid, -1,"SYNTAXE: /checkex [playerid]");
>     if(!IsPlayerConnected(targetid)) return SendClientMessage(playerid, -1,"This player isn't connected.");
>     GetPlayerIp(playerid,IpEx,sizeof(IpEx));
>     format(checkexString,sizeof(checkexString), "%s ( %i ) %s",ReturnPlayerName(targetid), targetid, IpEx);
> 	GetPlayerCountryDataAsString(targetid, dat);
> 	ShowPlayerDialog(playerid, 4874, DIALOG_STYLE_MSGBOX, checkexString, dat, "Close", "");
> 	return 1;
> }

**Comment by DarkQuery** [comment]
Update HTTP. "iphub.info/api.php?ip=%s&showtype1"


Showtype = 1 (XML Format)

**Comment by Southclaw** [comment]
By "I rearranged it and remodeled it in order to use the include then I used it in my code" do you mean this isn't directly an SS issue? And "But when the script I use on a hosted server hosting, so it does not work" do you mean it works normally but not on your hosting? If so, that's a problem with the host since they probably block HTTP I/O.

**Comment by DarkQuery** [comment]
Yes, I use it as a separately script (except for S & S), and if it then makes the host, so thank you, try another and see if it will do :-)

If that does not work, so we'll see, I'll try to write here again.

**Comment by DarkQuery** [comment]
How does it looks, this game hosting blocked HTTP?

**Comment by Kar2k** [comment]
iphub was supposed to expire yesterday if you look up the domain name. The expiry date still says 20th march 2016. It stopped working for a small period of time but it seems fine now.

**Comment by Southclaw** [comment]
These IP services seem to come and go (I think most are just side projects that don't really generate enough revenue to support themselves). Which is why I included the GeoIP code still, all you have to do is uncomment the line in a function called something like _ctr_useDatabase (?) but I remember it being buggy with sqlite-improved so I disabled it.

**Comment by DarkQuery** [comment]
Yesterday, he goes iphub.info but later he was back in operation, but I want to test whether it will work on other gaming providers and see what else was repeated as Southclaw says that the code (Country.pwn) works as intended and information from iphub.info is written into the game (SAMP Server)

**Comment by DarkQuery** [comment]
Southclaw, I wanted to ask, works on the local server? I GetPlayerCountryDataAsString stock (playerid, output [], len = sizeof (output))

**Comment by Southclaw** [comment]
If you connect on localhost, it will be a blank string or "localhost" I think.
