### ISSUE TITLE
SIF or YSI ?

### ISSUE THREAD

**Issue by DarkQuery** [Southclaw/ScavengeSurvive#192]
Hey, I have a problem with the file load-Save, I do not know why but it does not work, I tried the new YSI 3.1 and even SIF 1.2.5, but without result.

```
\sss/core/player/save-load.pwn(472) : error 017: undefined symbol "virtual"
\sss/core/player/save-load.pwn(472) : warning 215: expression has no effect
\sss/core/player/save-load.pwn(472) : error 001: expected token: ";", but found ")"
sss/core/player/save-load.pwn(472) : error 029: invalid expression, assumed zero
\sss/core/player/save-load.pwn(472) : fatal error 107: too many error messages on one line
```

http://prntscr.com/5wdldb (Old)

I looked into the archives and found the same problem, I looked at the responses under the theme, and I came across an answer from Southclaw but replace YSI and helped SIF

`itemid = CreateItem(itemtype, .virtual = 1);`

In stock parameter .virtual I do not see what it then be?

`stock CreateItem(ItemType:type, Float:x = 0.0, Float:y = 0.0, Float:z = 0.0, Float:rx = 1000.0, Float:ry = 1000.0, Float:rz = 1000.0, Float:zoffset = 0.0, world = 0, interior = 0, label = 1, applyrotoffsets = 1)`

**Comment by Southclaw** [comment]
The latest SIF has that parameter: https://github.com/Southclaw/SIF/blob/master/SIF/Item.pwn#L1550

**Comment by DarkQuery** [comment]
Indeed, this is the new SIF? I used the SIF, which you wrote here above, and blew me a lot of undefined symbols and the unknown parameters

\pawno\include\sss/core/world/tent.pwn(437) : warning 235: public function lacks forward declaration (symbol "OnItemArrayDataChanged")
\pawno\include\sss/core/world/craft-construct.pwn(127) : error 017: undefined symbol "GetItemFromButtonID"
\pawno\include\sss/core/world/craft-construct.pwn(133) : error 017: undefined symbol "_cft_FindCraftset"
\pawno\include\sss/core/world/craft-construct.pwn(136) : error 017: undefined symbol "IsValidCraftSet"
\pawno\include\sss/core/world/craft-construct.pwn(283) : error 017: undefined symbol "IsValidCraftSet"
\pawno\include\sss/core/world/workbench.pwn(189) : error 017: undefined symbol "_cft_FindCraftset"
\pawno\include\sss/core/admin/name-tags.pwn(53) : error 035: argument type mismatch (argument 14)
pawno\include\sss/core/admin/name-tags.pwn(54) : error 035: argument type mismatch (argument 14)
pawno\include\sss/core/item/plantpot.pwn(250) : warning 202: number of arguments does not match definition
\pawno\include\sss/core/item/plantpot.pwn(264) : warning 202: number of arguments does not match definition
\pawno\include\sss/core/item/plantpot.pwn(270) : warning 202: number of arguments does not match definition`

I used all the latest updated versions of files and include

**Comment by Southclaw** [comment]
Ah yes, SIF isn't updated on the repo, just use the last release of SS or an older commit. I'll get to it soon but I need to rewrite some of the documentation and clean some things up a bit first.

**Comment by DarkQuery** [comment]
Well, thanks for your answer, which you're probably planning to work on updating about SIF? It will be in the near future? It is not important exactly when will be published

Thank you.

**Comment by kadaradam** [comment]
DarkQuery, just uncomment:
- SetConstructionSetWorkbench() part from \sss\core\server\init.pwn
- CreateWorkBench() line from \sss\world\zones\sf.pwn
- #include "sss/core/world/workbench.pwn" and #include "sss/core/world/craft-construct.pwn" from the main file
And you'll be fine.

Also replace the name-tags.pwn where the errors are with this code:
`tags_Nametag[playerid] = CreateDynamic3DTextLabelEx(string, YELLOW, 0.0, 0.0, 0.0, 6000.0, playerid, _, 0, 6000.0, _, _, players, _, 1, 1, maxplayers, 1);
	tags_NametagLOS[playerid] = CreateDynamic3DTextLabelEx("[|                                           |]", BLUE, 0.0, 0.0, 0.0, 6000.0, playerid, _, 1, 6000.0, _, _, players, _, 1, 1, maxplayers, 1);`

The gamemode uses the old version of streamer, so we have to do some modification to make it work.
