### ISSUE TITLE
Missing keys for the settings.ini file

### ISSUE THREAD

**Issue by viruxe** [Southclaw/ScavengeSurvive#197]
```
[12:58:25] ERROR: key 'server/rules/0' not found.
[12:58:25] ERROR: key 'server/staff/0' not found.
[12:58:26] ERROR: key 'infomessage/messages/0' not found.
```
Still using the script created settings file.

**Comment by Southclaw** [comment]
Probably something to do with my knocked-together INI array system (the .../0 is an array index), I'll look into it.

**Comment by viruxe** [comment]
Manually adding these keys works. They just don't get added when building the default file the first time you run the server.
