### ISSUE TITLE
Multi-Language Support

### ISSUE THREAD

**Issue by Southclaw** [Southclaw/ScavengeSurvive#201]
Now that a module has been added to support multiple languages, translation must be done.

I will explain how the module works and the code syntax for sending messages based on a player's language.

Original code:
```
ChatMsg(playerid, YELLOW, " >  Language changed to English!");
```

New code:
```
ChatMsgLang(playerid, YELLOW, "LANGCHANGE");
```

The original string now exists in ```./scriptfiles/SSS/languages/English"```:
```
LANGCHANGE= >  Language changed to English!
```
Along with translations in other files, such as ```./scriptfiles/SSS/languages/English"```:
```
LANGCHANGE= >  Idioma alterado para Português
```

So to add a translation, replace the original static string with the new syntax and a unique "tag" for that particular string of text. Then add that string of text to the English translation file and your translated version to the respected file.

IMPORTANT:
Once you've added the original English version and your translated version, if there are other language files present you cannot leave out the tag you just added. You must add the English version to all other language files so the original string exists there until a translation for that language is added.

For example, I don't know French so until someone adds a French translation, this is what the file ```./scriptfiles/SSS/languages/French"``` looks like:
```
LANGCHANGE= >  Language changed to French (No translation yet)!
```

**Comment by viruxe** [comment]
The `languages` folder should be capitalized to conform with the rest of the folders in the scriptfiles folder.

**Comment by Southclaw** [comment]
I was actually going to lowercase all the scriptfiles directories (had some case confusion on linux, thought it would be simpler if everything is lowercase and dash separated).

**Comment by viruxe** [comment]
It appears that colors are not being parsed with translated strings.

**Comment by Southclaw** [comment]
Oh yeah I forgot about definitions needing to be put above usage! And yeah the C_BLUE things are constant definitions, you'll have to replace them with {colour} codes (but you can do that with sublime text search and replace).

**Comment by viruxe** [comment]
Should I first finish the English file so that a standard can be set?

**Comment by Southclaw** [comment]
Yeah that would be great!

**Comment by Southclaw** [comment]
Just a quick note, I added the replacements mentioned in my previous post. You can leave things like "C_YELLOW" but just replace the quote marks with {} (easy with regex search and replace)

https://github.com/Southclaw/ScavengeSurvive/blob/9a847d0fbc23e705d6c16fb4e03923717bc757d4/gamemodes/sss/core/server/language.pwn#L70-L94

I've also completed English definitions for all calls to ShowActionText, if anyone is planning to contribute please ensure you have the latest version of the code synced locally so you know what has already been done!

**Comment by Southclaw** [comment]
Latest English langfile is now on the repo.

**Comment by Southclaw** [comment]
Finished replacing the Msg/MsgF functions with new functions and done all the English entries for them. The new function name for regular messages (with or without format specifiers) is just:
```ChatMsg```

And language strings are sent using
```ChatMsgLang```

There's also an language string counter on startup:

```
Default language (English) has 157 entries.
Loading language 'Português (PT-PT)'...
Loaded! 65 entries, 92 missing entries
Loaded 1 languages
```
