### ISSUE TITLE
Language string format constants on load

### ISSUE THREAD

**Issue by Southclaw** [Southclaw/ScavengeSurvive#206]
Language module needs a simple replacement procedure to run when it loads each entry (not when it looks up an entry of course!) to replace things like key bindings and colours.

Examples of desired replacements:
- Colours, such as "{C_YELLOW}"
- Keys, such as "{KEYTEXT_INTERACT}"

**Comment by SizableRapter** [comment]
@Southclaw I'll look into the possibility of using a Phrase System, although wouldn't that mean we'd need a way to "save"/"load" these Phrases for use within the language system... I wouldn't exactly go about the route of "hard-coding" them into the gamemode itself.

I'm sure what specifically you'd like to do with it, is Phraser an option?

**Comment by Southclaw** [comment]
Can you elaborate on what this phrase system is and how it would work or how it's different to what's already implemented?
