### ISSUE TITLE
Crashdetect implementation

### ISSUE THREAD

**Issue by viruxe** [Southclaw/ScavengeSurvive#211]
While trying to disable the crashdetect plugin I saw you are including it's include in the main script but from what I've searched no native functions are implemented.

Are there any plans to implement some of it? Might be useful in the long run.

**Comment by Southclaw** [comment]
Ah yeah I did implement the callback once but it was removed for some reason (I used it temporarily once probably). Yeah it might be useful to utilise the API, I forgot what's available though.

**Comment by Patrik356b** [comment]
You can look into the plugin source to see what is available. AFIAK it was only an initialization function, but my memory could be corrupt
