### ISSUE TITLE
Compiler crashed ?

### ISSUE THREAD

**Issue by DarkQuery** [Southclaw/ScavengeSurvive#216]
Hi, I downloaded the latest S&S, I replaced the files but when it compiles and Pawn compiler crashes, what happened? Where could it be wrong?

**Comment by Southclaw** [comment]
I don't know and probably will never know! There's a ton of different things that can cause that.

Just remove includes one at a time and keep compiling until it crashes.

**Comment by DarkQuery** [comment]
My mistake, corrected, sorry.

Solved.
