### ISSUE TITLE
Drug effects

### ISSUE THREAD

**Issue by viruxe** [Southclaw/ScavengeSurvive#224]
`ERROR: Attempted to assign drug effects from malformed array, cell 0: 0` 

This happens everytime someone joins.

**Comment by Southclaw** [comment]
Yeah I've been meaning to check that out for a while. It's nothing to be worried about (no memory errors) just a little warning I added because I expected the drug array to always have *some*  data in it but apparently it has none if the player isn't under any drug effects.
