### ISSUE TITLE
Tree Module Additions

### ISSUE THREAD

**Issue by Southclaw** [Southclaw/ScavengeSurvive#228]
- Set harvest tool required (so it's not always a chainsaw, and can be hands/no item)
- Set harvest item (so it's not always logs, for cacti and bushes)
- Add Z offset parameter to species definitions so some models can be sank into the ground

Add berries and cactus water for crafting things like healing potions and poisons.

**Comment by Patrik356b** [comment]
Is there an axe in the game?

**Comment by Southclaw** [comment]
Unfortunately no, only chainsaw. I looked at objects to combine but there isn't really anything that looks good enough (plus SIF doesn't really support multi-model items).

**Comment by Patrik356b** [comment]
Though you could technically use the katana for bushes, tiny trees and other such plants. 

Another option is to attach a square or wedge object virtually to the cane weapon. (this might look silly though ) 

Having multiple object combinations would be really useful but I suspect it would take significant effort to add. 

I think I'll leave this issue for now and maybe revisit later

**Comment by viruxe** [comment]
What about making use of custom objects?

**Comment by Patrik356b** [comment]
The distribution of those. Every client would have to download them and install them correctly. 

This makes it not really worth the trouble.
(There might be a suitable object in the GamerX custom img file but I have not looked through it)
