### ISSUE TITLE
Double item pickup deletion with backpacks (possible any other Hold-to-pickup item)

### ISSUE THREAD

**Issue by Southclaw** [Southclaw/ScavengeSurvive#230]
/additem <anything>
/additem backpack
Hold F
Pickup is triggered twice

Does not work if:
/additem backpack
/additem <anything>

backpack itemid must be > other item.

**Comment by kadaradam** [comment]
It works for me if I do:
/additem backpack
/additem

Also safeboxes does the same thing with items nearby.

**Comment by kadaradam** [comment]
nice
