### ISSUE TITLE
Every Player gets knocked out after using hack interface

### ISSUE THREAD

**Issue by XFlawless1** [Southclaw/ScavengeSurvive#251]
After i used the hack interface, the players logged in and experienced many knocked outs
Says the log
And the players
And they were like
"There are random numbers on the screen, it was like hack interface,
I used it for some reason, bugged whole server,
Restart was required to fix so,
Doesn't affected Level 5-7
Affected players were level 3 level 2 and level 1 or either level 0's
The bug is in the "hack-interface.pwn"
Well try to reproduce its in the "https://github.com/Southclaw/ScavengeSurvive/commit/e063302e8e535e010f871029c523f708f9e6adb8"

**Comment by Southclaw** [comment]
Not sure why that would happen, only one player ID is referenced here: https://github.com/Southclaw/ScavengeSurvive/blob/c124ec7156e044291a9b04c95062cfeab0056a2b/gamemodes/sss/core/ui/keypad.pwn#L181-L222 I'll check it out later.

**Comment by kadaradam** [comment]
Dunno if that's on purpose, but all I see, that there is no return after `HideKeypad()` in the if statement, so line 210 still gets called even if the player fails.

**Comment by Southclaw** [comment]
Can't see how the original issue makes sense (do you mean it happens to all players at once randomly?).

Fixed what kadaradam mentioned though.
