### ISSUE TITLE
Fuel can behaviour

### ISSUE THREAD

**Issue by kadaradam** [Southclaw/ScavengeSurvive#252]
Fuel cans are defined as ammos and liquids right now. You can't transfer fuel "ammo" to weapons, because the liquid module is totally different. Maybe add liquid support to ammo types?

**Comment by Southclaw** [comment]
Yeah I knew this would happen, I'll sort out some communication between the two modules so it all works together.

**Comment by Southclaw** [comment]
I'm adding a `WEAPON_FLAG_LIQUID_AMMO` to item weapon definitions to indicate it uses a liquid type from liquid containers instead of regular ammo. The DefineItemTypeWeapon line for Flamer looks like this:

`DefineItemTypeWeapon(item_Flamer,			WEAPON_FLAMETHROWER,		liquid_Petrol,...`
