### ISSUE TITLE
Player crashes at some spawn points

### ISSUE THREAD

**Issue by XFlawless1** [Southclaw/ScavengeSurvive#253]
Whenever player dies, selects a spawn point,, gets died
XFlawless1 can Reproduce it on https://github.com/Southclaw/ScavengeSurvive/commit/f17e826cd37d78c57b1abe7a1e4b9600299557d0
@Southclaw's reply needed

**Comment by XFlawless1** [comment]
Coordinate the player crashed
I found 1
-380.1479,985.5676,10.5573,35.8264,0,0,0,0,0,0
Only NON-ADMINISTRATION gets crashed always, changing host, either loading/unloading fs doesn't worked. on https://github.com/Southclaw/ScavengeSurvive/commit/f17e826cd37d78c57b1abe7a1e4b9600299557d0

**Comment by Southclaw** [comment]
Any more info on this? Crash codes or anything? What kind of crash is it?

Most likely bad objects, try running the server without any custom maps.

**Comment by XFlawless1** [comment]
Okay i ll try and check it.

**Comment by XFlawless1** [comment]
Got 1 error from my players
Adding codes would spam added a pastebin link,
http://pastebin.com/sA6iuHji

**Comment by Southclaw** [comment]
Took me 5 seconds: http://forum.sa-mp.com/showthread.php?t=378577

Common error in SA:MP/SA engine, it's your objects or you're using some of the broken defence models that were disabled for exactly this reason.
