### ISSUE TITLE
After unloading a flamer with 100 ammo gives nothing

### ISSUE THREAD

**Issue by XFlawless1** [Southclaw/ScavengeSurvive#257]
After unloading a flamer with 100 petrol,
For every player, we reproduced it on "https://github.com/Southclaw/ScavengeSurvive/commit/ab1c2b249d6bdccdd72dae68f62961f08a46ee68"

**Comment by XFlawless1** [comment]
It must return with 20 litres of petrol if its 100 ammo but it returns with integer 0. -.-

**Comment by Southclaw** [comment]
Ah yes, the unloading fails because the petrol can uses a floating point value for it's content amount (since it's a liquid container). I'll probably just disable unloading for flamers and chainsaws anyway.
