### ISSUE TITLE
Unloading len knocks returns to NULL

### ISSUE THREAD

**Issue by XFlawless1** [Southclaw/ScavengeSurvive#258]
Len knocks is a weapon kind of, it is a weapon,,
Ammo used for it is .50 rounds, we tried to use the ammo from ammo tin of .50 rounds with 50 ammo
We failed and when we tried unloading to get ammo type Returned to NULL

**Comment by kadaradam** [comment]
Useless issue as always, everything works here. If you report an issue please speak English at least.

**Comment by XFlawless1** [comment]
Isn't it english?
You are better than me okay? Happy now?

**Comment by Southclaw** [comment]
All weapons produce nulls if they are unloaded when the ammoitem held inside the weapon is 0. When weapons spawn empty in the game world they have a value of -1 and the only way to make the ammoitem 0 is to *spawn the weapon* (I left this "bug" in the code intentionally) The Len Knocks is supposed to be a hidden rare item so stop spawning it in.
