### ISSUE TITLE
Unloading an MP5 returns with a petrol can

### ISSUE THREAD

**Issue by XFlawless1** [Southclaw/ScavengeSurvive#259]
Hello,
Again an bug and sorry for spamming but we tried to reproduce a bug 
"Unloading an MP5 returns with a petrol can" be reproduced @
https://github.com/Southclaw/ScavengeSurvive/commit/ab1c2b249d6bdccdd72dae68f62961f08a46ee68

**Comment by XFlawless1** [comment]
And yes you can take MP5's ammo with using flamer (LOADED)

**Comment by Southclaw** [comment]
Please keep one topic on each issue report.

Cannot reproduce the first thing you mentioned. Fixed the second thing, it's because the liquid ID uses the ammo type data field and the interact script had no way of differentiating liquid weapons to regular weapons.
