### ISSUE TITLE
Armour still spawns with -1 array of size, Clothes can't be wore

### ISSUE THREAD

**Issue by XFlawless1** [Southclaw/ScavengeSurvive#261]
After i do updated to https://github.com/Southclaw/ScavengeSurvive/commit/416435a52a23a80e1e3ee8518249829d5b2d9a25
We still got errors with armours,
Either clothes can't be wore on
https://github.com/Southclaw/ScavengeSurvive/commit/416435a52a23a80e1e3ee8518249829d5b2d9a25

**Comment by Southclaw** [comment]
Yeah it's due to the fix for #247, easy enough to fix by just reflecting the itemtype array sizes from before that commit for the specific items that require it.

**Comment by XFlawless1** [comment]
So use the outdated commit? https://github.com/Southclaw/ScavengeSurvive/commit/22adc59119758b4943dc35ec6e478f434b1196a5

**Comment by Southclaw** [comment]
Yes, it's only a organisational change obviously it won't affect anything, it just makes development easier since items will now have their MaxArrayData set in the item-specific module instead of in a massive list in `init.pwn`.

**Comment by XFlawless1** [comment]
Thanks for the help i will use the init.pwn from https://github.com/Southclaw/ScavengeSurvive/commit/22adc59119758b4943dc35ec6e478f434b1196a5
