### ISSUE TITLE
Animations under water

### ISSUE THREAD

**Issue by Trevor12515** [Southclaw/ScavengeSurvive#262]
Not really so much of a bug, more of a quality of life issue. When you go under water and start to drown, you can open up your inventory and get out an item and use it under water. Using it under water manages to make your breath to start going up while you should still be drowning. Also, not too sure if it's intended to be like this or not for water attacks or something. 

Here's a video: https://youtu.be/iFzZW__gquU

**Comment by Patrik356b** [comment]
I think is an oversight

**Comment by Southclaw** [comment]
Yeah I just sort of never fixed this one, it was always too insignificant compared to any other bug that was happening at the time.
