### ISSUE TITLE
Backpacks doesn't saves in tents

### ISSUE THREAD

**Issue by XFlawless1** [Southclaw/ScavengeSurvive#264]
In tents my players tried to save some backpacks,
Was written "Saved GEID ... etc.
"Saved"
On restart, it disappeared
in https://github.com/Southclaw/ScavengeSurvive/commit/935071e8ca6331accc7fbd01953633439aef913e

**Comment by Southclaw** [comment]
They never have and probably never will, unless the storage method is completely rewritten.

**Comment by Patrik356b** [comment]
I don´t see why you can´t make a temporary solution for this using an alternative method and invoke it as needed

**Comment by Southclaw** [comment]
The main reason for this is that the storage system isn't hierarchical and cannot really nest containers within containers. I did think of a solution to this using pointers to other modio tags within the saved data but never bothered.

It's one of those things that once players learn (either by asking or the hard way), they avoid it and don't often complain. There is of course information about it in `/help` but no one reads that anyway!
