### ISSUE TITLE
TNT's fail on 1100

### ISSUE THREAD

**Issue by XFlawless1** [Southclaw/ScavengeSurvive#271]
http://prntscr.com/bpeu7e
Logs above,
aswell the ,.... TNT again won't work, aswell the timed ied it doesn't gives an "Arm Bomb" At right near
Put away etc,,
Build 1100 Latest SIF.

**Comment by Southclaw** [comment]
You need to be more specific than "won't work" that doesn't help me at all (neither do the logs).

Timed explosives have this life cycle:
- player holds F to plant
- item is dropped
- when HoldAction is complete, 5 second timer is started
- after 5 seconds, explosion happens, which:
- affects nearby players (knockouts, bleeds)
- affects defences (removes hitpoints)

I just tested this and it all works fine.

**Comment by kadaradam** [comment]
Works for me too, I've just tested it. @XFlawless1  you are so annoying, what about you stop spamming your stupid issues? And learn to speak English please, noone understands you.

**Comment by XFlawless1** [comment]
Was wrong compiled by me, 
STFU @kadaradam
