### ISSUE TITLE
Players can't see each other moving

### ISSUE THREAD

**Issue by XFlawless1** [Southclaw/ScavengeSurvive#276]
On build https://github.com/Southclaw/ScavengeSurvive/commit/5191094f5c3130ef76617d27e78b4d0d089cf53e

**Comment by Southclaw** [comment]
Caused my my typo, this requires a `!` to invert the if check.  https://github.com/Southclaw/ScavengeSurvive/commit/a7ad1cd0fcdaf96ebdbdc360a7f31aef7032ad1b#commitcomment-18273953
