### ISSUE TITLE
Update item removal to support fixed SIF bug related to in-world items

### ISSUE THREAD

**Issue by Southclaw** [Southclaw/ScavengeSurvive#282]
Holstering items does not remove the item from the player any more on the latest SIF version where an item's "worldity" wasn't properly defined.

**Comment by trojan-sas** [comment]
is this fixed as after i update SIF to the lastest version i get what i show you on the video and for sure the old SIF can't handle the new version 1172

**Comment by trojan-sas** [comment]
what really happened is when i use the old version of SIF i can't pick up items from the ground unless its a weapon so all items i have to stand in the middle of it to pick it up 
and when i update to the new version hostler get bugged anything can be hostler duplicated one on back and one on hand like i show you

**Comment by AndreyLumineux** [comment]
I solved the problem. Tell me if i'm wrong;
I moved the condition:
`if(itm_Holder[itemid] != INVALID_PLAYER_ID)`
before the condition
`if(!Iter_Contains(itm_WorldIndex, _:itemid))`
So now the stock looks like that:
`stock RemoveItemFromWorld(itemid)
{
	sif_d:SIF_DEBUG_LEVEL_INTERNAL:ITEM_DEBUG("[RemoveItemFromWorld]");
	if(!Iter_Contains(itm_Index, _:itemid))
		return 0;

	if(itm_Holder[itemid] != INVALID_PLAYER_ID)
	{
		printf("[RemoveItemFromWorld] ERROR: Player %d was holding item %d that was in the world.", itm_Holder[itemid], itemid);
		RemoveCurrentItem(itm_Holder[itemid]);
	}

	if(!Iter_Contains(itm_WorldIndex, _:itemid))
		return 0;

	sif_d:SIF_DEBUG_LEVEL_CORE_DEEP:ITEM_DEBUG("[RemoveItemFromWorld] Item in world, destroying object");
	DestroyDynamicObject(itm_Data[itemid][itm_objId]);

	sif_d:SIF_DEBUG_LEVEL_CORE_DEEP:ITEM_DEBUG("[RemoveItemFromWorld] Destroying button");
	DestroyButton(itm_Data[itemid][itm_button]);

	sif_d:SIF_DEBUG_LEVEL_CORE_DEEP:ITEM_DEBUG("[RemoveItemFromWorld] Resetting array data");
	itm_ButtonIndex[itm_Data[itemid][itm_button]] = INVALID_BUTTON_ID;
	itm_Data[itemid][itm_objId] = -1;
	itm_Data[itemid][itm_button] = INVALID_BUTTON_ID;

	sif_d:SIF_DEBUG_LEVEL_CORE_DEEP:ITEM_DEBUG("[RemoveItemFromWorld] Removing item from world index");
	Iter_Remove(itm_WorldIndex, itemid);

	CallRemoteFunction("OnItemRemoveFromWorld", "d", itemid);

	#if defined DEBUG_LABELS_ITEM
		UpdateItemDebugLabel(itemid);
	#endif

	return 1;
}`

**Comment by Southclaw** [comment]
I'm back home now so I'll test this and if I can reproduce it I will try and get `master` up to date with the latest SIF version. I did make some `develop` related changes to SIF recently so that likely broke some features since I only really focus on the `develop` branch now since that's where all the new features are.

**Comment by Southclaw** [comment]
I should be able to get a release out today and push master up to build 1185+.
