### ISSUE TITLE
Start to use SHA256_PassHash

### ISSUE THREAD

**Issue by PT-Player** [Southclaw/ScavengeSurvive#305]
Hey,

Maybe is time to left the whirlpool and start to use SHA256_PassHash, this way you use an native function and dont need more one plugin loading...

Cheers.

**Comment by Southclaw** [comment]
I'd rather not cause a backwards compatibility issue. Whirlpool is still a fine algorithm and loading a plugin causes no problems or extra overheard to performance so I think this is unnecessary.
