### ISSUE TITLE
Xmas loot problem

### ISSUE THREAD

**Issue by NegativeIQ** [Southclaw/ScavengeSurvive#327]
Decided to play with these gamemode a bit and just compiled latest code from development branch and here is what i get. http://pastebin.com/kfETEHAG  ( Its easier to see on pastebin )

These -1 obviously should not happen...

**Comment by Southclaw** [comment]
I'll add a validity check for that since I assume you don't have [any loot data](https://github.com/Southclaw/ScavengeSurvive/tree/develop#loot-tables-scriptfileslootltb) loaded and the code should handle that case gracefully.

**Comment by NegativeIQ** [comment]
No i dont have anything in loot folder.

**Comment by Southclaw** [comment]
Fixed in 2d7d5d8af230698cea3292ed95ff91279405637e
