### ISSUE TITLE
Car armour (Develop branch)

### ISSUE THREAD

**Issue by NegativeIQ** [Southclaw/ScavengeSurvive#330]
Added Carmour offsets for Roadpain to scriptfiles.
When i spawn Roadpain i get these error:
`[ApplyArmourToVehicle] ERROR: Vehicle type (64) does not match carmour vehicle type (63).`

I looked at the code but i have no idea where the bug is. Easy fix would be to add -1 to [vehicletype](https://github.com/Southclaw/ScavengeSurvive/blob/develop/gamemodes/sss/core/vehicle/carmour.pwn#L163) variable, But im pretty sure its the wrong way...

[EDIT] Ok that is definitely not a fix, just tried and no objects attaches, didnt debug it but it probably tried to load objects for some other vehicle type and since its empty it didnt attach anything. But again i could be (and probably im) terribly wrong since i have no idea where the actual bug is...

**Comment by Southclaw** [comment]
That is especially odd, but it also reminds me that I should probably rewrite parts of the Carmour system (mostly the load method).

Since the existing Carmour types are private (they were made for and intended for my server and not for redistribution) the code shouldn't rely on hard-coding these modifications.

Aside from that though, I have no idea why this would be happening. It works fine on my end with my existing Carmour types.

I think I will move this system to external definitions via file (vehicle name on first line to link a Carmour definition to a vehicle type) and maybe I'll discover the source of this issue.

**Comment by NegativeIQ** [comment]
I will try to find or at least narrow down where the bug is, but that will probably take time since im still unfamiliar with the script. Anyway moving everything to files would be great thing, except the loot spawns as it would drastically increase server startup time.

**Comment by Southclaw** [comment]
Yeah, that's one reason I've always kept loot spawns hard-coded into the `world` "module".

**Comment by NegativeIQ** [comment]
Ok found one piece of the problem, it's me. I used wrong format in scriptfiles file and sscanf was failing at parsing string (I just assumed it will be straight forward modelid and offsets without "function"). But i still had to add that -1 to pass that check in ApplyArmourToVehicle like i tried before, so issue is still here as i have no idea where the id's get messed up...

**Comment by Southclaw** [comment]
Please confirm this fixes the issue.

The new system works like this:
`/scriptfiles/carmour/` files are loaded automatically. The filename of each file must be a valid vehicle name ("Doomrider" for example, which is a vehicle type defined with the Dunerider model made specifically for carmour modifications). Invalid vehicle names throw an error. Valid vehicle types have the objects added automatically without the need to call a function to link them in `init.pwn` so this should be much easier.

However, I haven't come across any off-by-one errors, it's all working fine with 5 Carmour mods loaded.

**Comment by NegativeIQ** [comment]
Sorry for a bit late reply. I removed amxBacktrace for test, everything else is stock from latest master (Last commit Southclaws/ScavengeSurvive@7acdc0a)
> [OnGameModeInit] Initialising 'Carmour'...
> [16:57:48] Vehicle type from name 'Roadpain.map' is invalid

As you can see for starters .map does not belong there, but when i fixed that everything loaded fine (without off by one mismatch). Would send pull request but i didnt use git as i have some problems with OS atm.
