### ISSUE TITLE
Add the ability to replace the "locksmith"

### ISSUE THREAD

**Issue by viruxe** [Southclaw/ScavengeSurvive#64]
Add the ability to replace the lock on an already locked vehicle with the condition that it is open.

**Comment by Southclaw** [comment]
Screw what I said back in 2014, that's way too complicated!

I'll just create a "Lock Breaker" item that requires complex crafting, it should be hard enough to craft that people only make it if they *really really* want to get into a specific vehicle. (similar to the hack device, maybe harder).

Suggestions are welcome!

**Comment by Patrik356b** [comment]
I'd base it on the hack device but replace X with screwdriver to differentiate the recipes
