### ISSUE TITLE
Hax detect

### ISSUE THREAD

**Issue by viruxe** [Southclaw/ScavengeSurvive#78]
s0beit automaticly has infinite oxygen enabled.

With that in mind:
- Blackout screen and aim at the sky
- Place player underwater for ~30 seconds (enough time for the oxygen bar to run out and start loosing health)
- Check if player lost health past that point or not
- If player didn't loose any health report/ban else teleport back to the previous position

**Comment by Patrik356b** [comment]
Make sure to position the player above the bottom of waterhole otherwise the game will not detect that your currently underwater

**Comment by Southclaw** [comment]
I've abandoned this idea now anyway! Got a much better anticheat solution coming soon anyway.
