### ISSUE TITLE
holster bug

### ISSUE THREAD

**Issue by PatchwerkQWER** [Southclaw/ScavengeSurvive#88]
When i take my weapon from holster and someone give me item (big item = "SPECIAL_ACTION_CARRY") i'll in bug. I can't drop new item, i can't anything.

**Comment by Southclaw** [comment]
Marking for a fix:
Duplicate this code with OnPlayerGiveItem:
https://github.com/Southclaw/ScavengeSurvive/blob/master/gamemodes/SS/Core/Char/Holster.pwn#L319-L339
